platform: linux
image_resource:
  type: docker-image
  source:
    repository: relintdockerhubpushbot/cf-test-runner

inputs:
  - name: env-metadata
  - name: cf-k8s-networking-ci

run:
  path: cf-k8s-networking-ci/ci/tasks/scale/pave-cf-for-scale-tests.sh
