platform: linux

image_resource:
  type: docker-image
  source:
    repository: gcr.io/cf-routing-desserts/ci-image-metadata-annotator
    username: _json_key
    password: ((gcp_gcr_desserts_service_account_key))

inputs:
  - name: cf-k8s-networking
  - name: initial-image
  - name: cf-k8s-networking-ci

outputs:
  - name: labels

run:
  path: cf-k8s-networking-ci/ci/tasks/docker/build-image-labels.sh
